[WIP] Standardize SSL settings
logstash-plugins/logstash-input-http pull request #165
Opened 2023-03-31 16:52 UTC by edmocosta

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

---
Closes https://github.com/elastic/logstash/issues/14928

2023-04-04 15:06 UTC, andsel requested changes
Left some comments to improve, but we are quite close to the finish.

2023-04-04 16:04 UTC, edmocosta commented on src/main/java/org/logstash/plugins/inputs/http/util/SslSimpleBuilder.java
> +
That would be nice! Both plugins share a lot of code actually (and requirements). We've started a spike to build the foundation for a common library (https://github.com/elastic/logstash/issues/14973). After building it, the next step would be creating mixing(s) to handle all the SSL settings/clients the plugins currently support.

2023-04-04 17:17 UTC, andsel commented on src/test/java/org/logstash/plugins/inputs/http/util/SslSimpleBuilderTest.java
> +    }
In the `testBuildContextWithClientAuthentication` it's using 2 times, so in that case wouldn't be ideal to identify what broke, unless we analyze the stack trace.
I think that the method is an implicit form of `if`s in test code, if we inline the helper method in the tests, we have `if`s in test code.

Hypothetically using the refactoring proposed the test code becomes more readable:
```java
    @Test
    void testBuildContextWithClientAuthentication() throws Exception {
        assertSslSimpleBuilderBuildContextWhenModeIsRequired(createSslSimpleBuilder()
                .setClientAuthentication(SslClientVerifyMode.REQUIRED, new String[]{CA})
        );

        assertSslSimpleBuilderBuildContextWhenModeIsOptional(createSslSimpleBuilder()
                .setClientAuthentication(SslClientVerifyMode.OPTIONAL, new String[]{CA})
        );
    }

    @Test
    void testBuildContextWithNoClientAuthentication() throws Exception {
        SslSimpleBuilder sslSimpleBuilder = createSslSimpleBuilder()
                .setClientAuthentication(SslClientVerifyMode.NONE, new String[]{CA});

        assertSslSimpleBuilderBuildContextWhenModeIsNone(sslSimpleBuilder);
    }
```


```java
    private void assertSslSimpleBuilderBuildContextWhenModeIsNone(SslSimpleBuilder sslSimpleBuilder) throws Exception {
        final SSLEngine sslEngine = createSSLEngineFromBuilder(sslSimpleBuilder);

        assertEquals(SslClientVerifyMode.NONE, sslSimpleBuilder.getVerifyMode());

        assertFalse(sslEngine.getNeedClientAuth());
        assertFalse(sslEngine.getWantClientAuth());
    }


    private void assertSslSimpleBuilderBuildContextWhenModeIsOptional(SslSimpleBuilder sslSimpleBuilder) throws Exception {
        final SSLEngine sslEngine = createSSLEngineFromBuilder(sslSimpleBuilder);

        assertEquals(SslClientVerifyMode.OPTIONAL, sslSimpleBuilder.getVerifyMode());

        assertFalse(sslEngine.getNeedClientAuth());
        assertTrue(sslEngine.getWantClientAuth());
    }

    private void assertSslSimpleBuilderBuildContextWhenModeIsRequired(SslSimpleBuilder sslSimpleBuilder) throws Exception {
        final SSLEngine sslEngine = createSSLEngineFromBuilder(sslSimpleBuilder);

        assertEquals(SslClientVerifyMode.REQUIRED, sslSimpleBuilder.getVerifyMode());

        assertTrue(sslEngine.getNeedClientAuth());
        assertFalse(sslEngine.getWantClientAuth());
    }


    private SSLEngine createSSLEngineFromBuilder(SslSimpleBuilder sslSimpleBuilder) throws Exception {
        final SslContext context = sslSimpleBuilder.build();

        assertTrue(context.isServer());

        final SSLEngine sslEngine = context.newEngine(ByteBufAllocator.DEFAULT);
        assertThat(sslEngine.getEnabledCipherSuites(), equalTo(sslSimpleBuilder.getCiphers()));
        assertThat(sslEngine.getEnabledProtocols(), equalTo(sslSimpleBuilder.getProtocols()));
        return sslEngine;
    }
```    
----

However if you don't accept the change, there a couple of nitpicks:
- the variable  `SslSimpleBuilder` should be lowercase started
- the `if`s are a `switch` statement, so using switch would grant that if future we don't miss any new enum value added to  `SslClientVerifyMode`

2023-04-04 17:20 UTC, andsel commented on src/main/java/org/logstash/plugins/inputs/http/util/SslSimpleBuilder.java
> +
:+1: maybe we can add an item in the task list in #14905 to track this and don't lose it

2023-04-05 09:09 UTC, andsel approved these changes
LGTM

2023-04-05 13:19 UTC, merged